version: "3.4"

services:
  mysql:
    image: mysql:5.6
    env_file:
      - env.d/development/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

  elasticsearch:
    image: fundocker/openshift-elasticsearch:6.6.2

  app:
    build:
      context: .
      target: production
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    image: aresthelord/richie:pro_1
    # env_file:
    #     - env.d/development/common
    #     - env.d/development/mysql
    environment: 
      # Django
      DJANGO_SETTINGS_MODULE: settings
      DJANGO_CONFIGURATION: Production
      DJANGO_SECRET_KEY: ThisIsAnExampleKeyForDevPurposeOnly
      #DJANGO_ALLOWED_HOSTS: "*"
      # Python
      PYTHONUNBUFFERED: 1
      DB_ENGINE: django.db.backends.mysql
      DB_HOST: "${DB_HOST:-mysql}"
      DB_NAME: richie
      DB_USER: fun
      DB_PASSWORD: pass
      DB_PORT: 3306
    ports:
        - "8070:8000"
    volumes:
      - .:/app
      - ./data/static:/data/static
      - ./data/media:/data/media
      - ./data/smedia:/data/smedia
    depends_on:
      - "${DB_HOST:-mysql}"
      - "elasticsearch"
      - redis-sentinel
    stdin_open: true
    tty: true

  node:
    image: circleci/node:10
    working_dir: /app/src/frontend
    user: "${DOCKER_USER:-1000}"
    volumes:
      - .:/app

  crowdin:
    image: fundocker/crowdin:2.0.27
    volumes:
      - ".:/app"
    env_file:
      - env.d/development/crowdin
    user: "${DOCKER_USER:-1000}"
    working_dir: /app

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:6.0-debian-10
    depends_on:
      - redis-primary
      - redis-replica1
      - redis-replica2
    environment:
      - REDIS_MASTER_HOST=redis-primary

  redis-primary:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master

  redis-replica1:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary

  redis-replica2:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
